USE libraryportal_db;

INSERT INTO books(title, author, description, genre, audience, isCheckedOut, createdAt, updatedAt)
VALUE ("The Tommyknockers", "King, Steven", "Something was happening in Bobbi Anderson''s idyllic small town of Haven, Maine.  Something that gave every man, woman, and child in Haven powers far beyond those of ordinary mortals. What could be the reason of these strange powers?", "Horror", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
	   ("Crazy Rich Asians", "Kwan, Kevin", "When New Yorker Rachel Chu agrees to spend the summer in Singapore with her boyfriend, she finds out the he is not the man she thought he was.", "Comedy", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Alaskan Holiday", "Macomber, Debbie", "Josie Avery takes a summer position cooking at a lakeside lodge in the remote Alaskan town of Ponder. She falls for the rustic charm of a local man.  Now Josie must choose moving back to Seattle for a dream job, or staying in Ponder with a man she is quickly coming to love.", "Romance", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Squirm", "Hiaasen, Carl", "This summer Billy Dickens will fly across the country, hike a mountain, float a river, dodge a grizzly bear, shoot down a spy drone, save a neighbor's cat, save an endangered panther, and try to save his own father.", "Drama", "Young Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Corduroy Takes a Bow", "Davis, Viola", "When Courduroy goes to the theatre for the first time, it so magnificent and exciting that he just can't help heading out on his own to explore. From the orchestra pit to the prop table to the dressing rooms, Corduroy sees it all.", "Comedy", "Children", false,"2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("The VanderBeekers and the Hidden Garden", "Glaser Yan, Karina", "When catastrophe strikes their beloved upstairs neighbor, Jessie, Oliver, Hycacinth, and Laney's sleepy summer transforms in an instant as the children band together to do what they do best: make a plan.", "Drama", "Young Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Ready Player One", "Cline, Ernest", "Wade Watts really only feels alive when he is jacked into the virtual utopia known as the OASIS. He is devoted his life to studying puzzles that could change his life forever. When he finds the first clue, he realizes that other players will do anything to stop him, including trying to kill him.", "Science Fiction", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("A Winter's Promise", "Hildegarde, Serle", "Ophelia cares little about apperances. Her ability to read the past of objects is unmatched in all of Anima and, what's more, she possesses the ability to travel through mirrors.  Her idyllic life is disrupted, however, when she is promised in marriage to Thorn.  She must leave all she knows behind to follow her finace to a world where danger lurks around every corner.", "Fantasy", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Lethal White", "Galbraith, Robert", "When Billy, a troubled young man, comes to private eye Cormoran Strike’s office to ask for his help investigating a crime he thinks he witnessed as a child, Strike is left deeply unsettled. While Billy is obviously mentally distressed, and cannot remember many concrete details, there is something sincere about him and his story. But before Strike can question him further, Billy bolts from his office in a panic. Will Strike be able to solve the mystery Billy has opened up before him?", "Mystery", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Long Way Down", "Reynolds, Jason", "An ode to Put the Damn Guns Down, this is National Book Award finalist and New York Times bestseller Jason Reynolds’s fiercely stunning novel that takes place in sixty potent seconds—the time it takes a kid to decide whether or not he’s going to murder the guy who killed his brother.", "Drama", "Young Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("The Chase", "Kennedy,Elle", "Everyone says opposites attract. And they must be right, because there’s no logical reason why I’m so drawn to Colin Fitzgerald. I don’t usually go for tattoo-covered, video-gaming, hockey-playing nerd-jocks who think I’m flighty and superficial. His narrow view of me is the first strike against him. It doesn’t help that he’s buddy-buddy with my brother. The only problem is, he has made it clear he's not interested in me.", "Romance", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("I am Watching You", "Driscoll, Teresa", "When Ella Longfield overhears two attractive young men flirting with teenage girls on a train, she thinks nothing of it—until she realises they are fresh out of prison and her maternal instinct is put on high alert. But just as she’s decided to call for help, something stops her. The next day, she wakes up to the news that one of the girls—beautiful, green-eyed Anna Ballard—has disappeared. A year later, Anna is still missing and Ella is wracked with guilt over what she failed to do, and she's not the only one who can't forget. Someone is sending her threatening letters.  Someone knows where Anna is, and they're not telling, but they are watching Ella.", "Suspense", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Fahrenheit 451", "Bradbury, Ray", "Guy Montag is a fireman. In his world, where television rules and literature is on the brink of extinction, firemen start fires rather than put them out. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. When he meets Clarisse, she introduces him to a world through the ideas in books instead of the mindless chatter of television. Montag starts to question everything he has ever known.  He starts hiding books in his home, and when it is discovered, the fireman must run for his life.", "Drama", "Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Madeline", "Bemelmans, Ludwing", "Madeline may have been the smallest of the twelve little girls who always walked in two straight lines, but she was the bravest—to the tiger in the zoo, Madeline just said “pooh- pooh”.", "Comedy", "Children", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("The Call of the Wild", "London, Jack", "When Buck is stolen from his kind family, he must quickly learn a new set of survival rules as he is taken away to the gold-crazed North by unsavory men.", "Drama", "Children", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("The Infinite Pieces of Us", "Crane Rebekah", "Pondering math problems is Esther Ainsworth’s obsession. If only life’s puzzles required logic. Her stepfather’s solution? Avoidance. He’s exiled the family to Truth or Consequences, New Mexico, to erase a big secret from Esther’s past. So much for the truth. Now for the consequences: an empty swimming pool, a water-sucking cactus outside her window, a goldfish rescued from a church festival, and Esther’s thirst for something real.", "Drama", "Young Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("To All the Boy's I've Loved Before", "Han, Jenny", "Sixteen-year-old Lara Jean Song keeps her love letters in a hatbox her mother gave her. They aren’t love letters that anyone else wrote for her; these are ones she’s written. One for every boy she’s ever loved—five in all. When she writes, she pours out her heart and soul and says all the things she would never say in real life, because her letters are for her eyes only. Until the day her secret letters are mailed, and suddenly, Lara Jean’s love life goes from imaginary to out of control.", "Romance", "Young Adult", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("A Wrinkle in Time", "L'Engle, Madeleine", "Meg Murry, her little brother Charles Wallace, and their mother are having a midnight snack on a dark and stormy night when an unearthly stranger appears at their door. He claims to have been blown off course and goes on to tell them that there is such a thing as a tesseract, which, if you didn't know, is a wrinkle in time. Meg's father had been experimenting with time travel when he suddenly disappeared. Will Meg, Charles Wallace, and their friend Calvin outwit the forces of evil as they search through space for their father?", "Mystery", "Children", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("You Don't Know Everything, Jilly P!", "Gino, Alex", "A big fantasy reader, Jilly makes a connection online with another fantasy fan, Derek, who is a Deaf, Black ASL user. She goes to Derek for help with Emma but doesn't always know the best way or time to ask for it. As she and Derek meet in person, have some really fun conversations, and become friends, Jilly makes some mistakes . . . but comes to understand that it's up to her, not Derek to figure out how to do better next time--especially when she wants to be there for Derek the most.", "Drama", "Children", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
       ("Monstrous Devices", "Love, Damien", "On a winter’s day in a British town, twelve-year old Alex receives a package in the mail: an old tin robot from his grandfather. “This one is special,” says the enclosed note, and when strange events start occurring around him, Alex suspects this small toy is more than special; it might be deadly.", "Mystery", "Children", false, "2018-10-01 6:23:00", "2018-10-01 6:23:00")
