USE libraryportal_db;

INSERT INTO media (title, author, description, genre, audience, createdAt, updatedAt)
VALUES  ("IT", "Palmer, Chase", "A group of bullied kids band together when a monster, taking the appearance of a clown, begins hunting children.", "Horror", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
	    ("Teenage Mutant Ninja Turtles", "Bay, Micheal", "After super villain Shredder escapes custody, he joins forces with mad scientist Baxter Stockman and two dimwitted henchmen, Bebop and Rocksteady, to unleash a diabolical plan to take over the world. As the Turtles prepare to take on Shredder and his new crew, they find themselves facing an even greater evil with similar intentions: the notorious Krang.", "Comedy", "Children", "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("All Roads Lead to Rome", "Lemhagen, Ella", "Maggie is an uptight, single mother who, in an effort to reconnect with her troubled teen daughter Summer, takes her to the Tuscan village where she used to visit in her youth. There Maggie runs into her former lover Luca and his mother, Carmen. When Summer and Carmen impulsively steal Luca's car and race off to Rome, Maggie and Luca follow in close pursuit.", "Comedy", "Adult" ,   "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("Reservoir Dogs", "Tarantino, Quentin", "After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.", "Drama", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Shawshank Redemption", "Darabont, Frank", "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "Drama", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Hangover", "Phillips, Todd", "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.", "Comedy", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("Moana", "Clements, Ron", "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the Ocean's call to seek out the Demigod to set things right.", "Comedy", "Children",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("Hotel Transylvania", "Genndy, Tartakovsky", "Dracula, who operates a high-end resort away from the human world, goes into overprotective mode when a boy discovers the resort and falls for the count's teenaged daughter.",  "Comedy", "Children",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Godfather", "Ford, Francis", "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", "Gangster", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("Star Wars: The Last Jedi", "Johnson, Rian", "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares for battle with the First Order.", "Science Fiction", "Young Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Incredibles", "Bird, Brad", "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.", "Comedy", "Children",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Fifth Element", "Besson, Luc", "In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.", "Science Fiction", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Matrix", "Wachowski, Lana", "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", "Science Fiction", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Lord of the Rings - The Fellowship of the Ring", "Jackson, Peter", "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", "Fantasy", "Adult", "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Shining", "Kubrick, Stanley", "A family heads to an isolated hotel for the winter where an evil spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.", "Horror", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("Inception", "Nolan, Christopher", "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.", "Suspense", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("The Neverending Story", "Petersen, Wolfgang", "A troubled boy dives into a wondrous fantasy world through the pages of a mysterious book.", "Fantasy", "Adult",  "2018-10-01 6:23:00", "2018-10-01 6:23:00"),
        ("Mary Poppins", "Stevenson, Robert", "In turn of the century London, a magical nanny employs music and adventure to help two neglected children become closer to their father.", "Comedy", "Children",  "2018-10-01 6:23:00", "2018-10-01 6:23:00")
